version: 2
updates:
  - package-ecosystem: "npm" # covers pnpm as well
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
